version: '3.4'

services:
  liswebapp:
    image: ${DOCKER_REGISTRY-}liswebapp
    build:
      context: .
      dockerfile: LISWebAPP/Dockerfile

  liswebapi:
    image: ${DOCKER_REGISTRY-}liswebapi
    build:
      context: .
      dockerfile: LISWebAPI/Dockerfile


  lisconsoleapp:
    image: ${DOCKER_REGISTRY-}lisconsoleapp
    build:
      context: .
      dockerfile: LISConsoleApp/Dockerfile

